configuration:
  api:
    jobsUrl: http://test.swipejobs.com/api/jobs
    workersUrl: http://test.swipejobs.com/api/workers
logging:
  level:
    org.springframework.web: ERROR
    com.swipejobs.matchingengine: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"